### ISSUE TITLE
How to add 2 ble devices in the config files

### ISSUE THREAD

**Issue by Minims** [dominikberse/homeassistant-bluetooth-mesh#13]
Hello,

How to add 2 ble devices in the config files ? The second one is never read

Is it ok like this 

```
---
mqtt:
  broker: <mqtt_broker>
  # username: <username>
  # password: <password>
  node_id: mqtt_mesh
mesh:
  hass_device_id:
    uuid: <bluetooth_mesh_device_uuid>
    name: <hass_device_name>
    type: light             # Only type supported for now.
    relay: false            # Whether this node should act as a Bluetooth Relay
  hass_device_id_2:
    uuid: <bluetooth_mesh_device_uuid>
    name: <hass_device_name>
    type: light             # Only type supported for now.
    relay: false            # Whether this node should act as a Bluetooth Relay

```

or like this 

```
---
mqtt:
  broker: <mqtt_broker>
  # username: <username>
  # password: <password>
  node_id: mqtt_mesh
mesh:
  - hass_device_id:
      uuid: <bluetooth_mesh_device_uuid>
      name: <hass_device_name>
      type: light             # Only type supported for now.
      relay: false            # Whether this node should act as a Bluetooth Relay
  - hass_device_id_2:
      uuid: <bluetooth_mesh_device_uuid>
      name: <hass_device_name>
      type: light             # Only type supported for now.
      relay: false            # Whether this node should act as a Bluetooth Relay
  
```

or it's not managed ?
